import { LegalPage } from '@/components/web/LegalPage';

const sections = [
  { title: 'Who controls your information', body: 'DOIT AI is the controller of personal information used to provide this service. You can contact DOIT AI about privacy or exercise your rights at ofoegbuharreth@gmail.com.' },
  { title: 'Information you provide', body: 'We process account details such as your email and profile name, together with goals, actions, progress logs, check-ins, reminder choices, calendar items, focus sessions, device-session information, subscription status, referral attribution, founding-member status, product feedback, cancellation feedback and coach conversations you choose to save. Support messages may include information you choose to send us.' },
  { title: 'Why we use it and our lawful bases', body: 'We use account and goal information to perform our contract with you: signing you in, generating and adapting plans, syncing devices, showing progress, providing reminders and operating paid features. We use limited technical and security information for our legitimate interests in preventing abuse, diagnosing failures and keeping DOIT reliable. We process billing records where needed to perform the subscription contract and meet legal obligations. Optional product analytics is based on your choice and can be disabled in Profile.' },
  { title: 'AI processing', body: 'When you request an AI-generated plan or adaptation, the relevant goal details and instructions are sent to OpenAI to produce the response. DOIT configures API response storage off for these requests. Do not enter information you do not want processed for planning, and avoid unnecessary medical, financial, legal or other highly sensitive personal information.' },
  { title: 'Service providers and recipients', body: 'Supabase provides authentication, database and server functions. OpenAI provides AI processing. Stripe processes web subscriptions; a native Android release may use Google Play and RevenueCat. Resend delivers operational email. Cloudflare hosts the web app. When enabled, Sentry receives technical crash diagnostics and PostHog receives limited product events. Product analytics excludes goal titles, action text, email addresses and coach messages.' },
  { title: 'Payments', body: 'Stripe processes web and installed-web-app subscriptions. Google Play and RevenueCat may process subscriptions in a future native Android store release. DOIT AI receives identifiers and subscription status needed to grant access, but does not receive or store your full card number.' },
  { title: 'International transfers', body: 'Some providers may process information outside the United Kingdom. Where required, we rely on the provider’s contractual safeguards, adequacy arrangements or another lawful transfer mechanism. You can contact us for more information about safeguards relevant to your account.' },
  { title: 'Retention', body: 'Account and goal information is kept while your account is active and is deleted when you use Delete account, subject to limited records we must retain for legal, fraud-prevention, dispute or security purposes. Billing providers retain transaction records under their own legal obligations. Support, cancellation and operational records are kept only for as long as reasonably needed to resolve the issue, understand service quality or meet legal requirements.' },
  { title: 'Your rights and choices', body: 'Depending on the circumstances, UK data-protection law may give you rights to access, correct, erase, restrict or object to processing, and to receive a portable copy of information. You can export your DOIT data and permanently delete your account from Profile. You can disable optional product analytics in Profile. Contact us to exercise another right. You may also complain to the UK Information Commissioner’s Office at ico.org.uk.' },
  { title: 'Security', body: 'We use encrypted connections, account authentication, row-level database access controls and restricted server-side credentials designed to protect your information. No online service can guarantee absolute security. Contact us promptly if you believe your account or information has been compromised.' },
  { title: 'Children', body: 'DOIT AI is not intended for children under 13. If we learn that an account belongs to a child under 13, we will take steps to delete it. Users under 18 should use DOIT AI with permission from a parent or guardian.' },
  { title: 'Changes', body: 'We may update this notice as DOIT AI develops. Material changes will be reflected here with a revised update date.' },
];

export default function PrivacyScreen() {
  return <LegalPage title="Privacy Policy" intro="A clear explanation of what DOIT AI uses, why it is used, and the controls you have." sections={sections} />;
}
