import Ionicons from '@expo/vector-icons/Ionicons';
import { router, useLocalSearchParams } from 'expo-router';
import { useMemo, useRef, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Switch, View } from 'react-native';
import Animated, { FadeInDown, Layout } from 'react-native-reanimated';

import { ScreenHeader } from '@/components/navigation/ScreenHeader';
import { SharePlanCard } from '@/components/share/SharePlanCard';
import { Button, Card, Input, Screen, SectionHeader, Text } from '@/components/ui';
import { useSubscription } from '@/hooks';
import { captureException, track } from '@/services/observability';
import { DEFAULT_SHARE_OPTIONS, SHARE_CARD_FORMATS, SHARE_CARD_TEMPLATES, shareCardSummary, type ShareCardFormat, type ShareCardOptions, type ShareCardTemplate } from '@/services/share-card';
import { copyShareText, downloadShareCard, exportShareCard, shareShareCard } from '@/services/share-card-export';
import { useAppStore } from '@/stores';
import { colors, radius, spacing } from '@/theme';

const accents = ['#B7FF2A', '#9B7BFF', '#2CC8E2', '#FFB020', '#FF6680'];

export default function SharePlanScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const { goals, milestones, tasks } = useAppStore(); const { isPro, isMax, planName } = useSubscription();
  const goal = goals.find((item) => item.id === id); const goalMilestones = milestones.filter((item) => item.goalId === id); const goalTasks = tasks.filter((item) => item.goalId === id);
  const previewRef = useRef<View>(null); const [template, setTemplate] = useState<ShareCardTemplate>('progress'); const [format, setFormat] = useState<ShareCardFormat>('square');
  const [options, setOptions] = useState<ShareCardOptions>(DEFAULT_SHARE_OPTIONS); const [accent, setAccent] = useState(colors.accent); const [subtitle, setSubtitle] = useState('');
  const [working, setWorking] = useState<'download' | 'share' | 'copy'>(); const [notice, setNotice] = useState('');
  const summary = useMemo(() => goal ? shareCardSummary(goal, goalMilestones, goalTasks) : '', [goal, goalMilestones, goalTasks]);
  if (!goal) return <Screen><ScreenHeader title="Share plan" onBack={() => router.back()} /><Card><Text variant="heading">Goal not found.</Text></Card></Screen>;
  if (!isPro) return <Screen scrollable contentContainerStyle={styles.screen}><ScreenHeader title="Share plan" onBack={() => router.back()} /><Animated.View entering={FadeInDown.springify()}><Card style={styles.locked}><View style={styles.lockIcon}><Ionicons name="images" color={colors.accent} size={27} /></View><Text variant="eyebrow" color="accent">DOIT PRO</Text><Text variant="title" style={styles.center}>Turn your plan into something worth sharing.</Text><Text color="secondary" style={styles.center}>Shareable Plan Cards are available with DOIT Pro and MAX. Create polished, private PNGs for progress updates and social posts.</Text><Button label="Upgrade to Pro" icon="diamond" onPress={() => { track('share_card_upgrade_clicked', { source: 'goal_share' }); router.push('/pro?tier=pro'); }} /><Button label="View plans" variant="secondary" onPress={() => router.push('/pro')} /><Pressable onPress={() => router.back()}><Text variant="label" color="secondary">Not now</Text></Pressable></Card></Animated.View></Screen>;

  const setOption = (key: keyof ShareCardOptions, value: boolean) => setOptions((current) => ({ ...current, [key]: value }));
  const makeImage = async (action: 'download' | 'share') => { setWorking(action); setNotice(''); try { const uri = await exportShareCard(previewRef, format); track('share_card_exported', { format, template, plan: planName }); if (action === 'download') await downloadShareCard(uri); else await shareShareCard(uri); track(action === 'download' ? 'share_card_downloaded' : 'share_card_shared', { format, template, plan: planName }); setNotice(action === 'download' ? 'PNG ready.' : 'Share sheet opened.'); } catch (error) { captureException(error, { area: 'share_card_export', format }); setNotice(error instanceof Error ? error.message : 'Could not create the image.'); } finally { setWorking(undefined); } };
  const copy = async () => { setWorking('copy'); setNotice(''); try { await copyShareText(summary); track('share_card_copied', { format, template, plan: planName }); setNotice('Plan summary copied.'); } catch (error) { setNotice(error instanceof Error ? error.message : 'Could not copy the summary.'); } finally { setWorking(undefined); } };

  return <Screen scrollable contentContainerStyle={styles.screen}><ScreenHeader title="Create share card" onBack={() => router.back()} />
    <View style={styles.heading}><Text variant="eyebrow" color="accent">PRIVATE BY DEFAULT</Text><Text variant="title">Make your progress visible.</Text><Text color="secondary">Only the fields switched on below are rendered. Your account, notes and private history never appear.</Text></View>
    <Animated.View layout={Layout.springify()} style={[styles.previewFrame, format === 'vertical' && styles.previewVertical, format === 'landscape' && styles.previewLandscape]}><View ref={previewRef} collapsable={false} style={styles.preview}><SharePlanCard goal={goal} milestones={goalMilestones} tasks={goalTasks} format={format} template={template} options={options} accent={accent} subtitle={subtitle} /></View></Animated.View>
    <SectionHeader eyebrow="STYLE" title="Choose a look" /><View style={styles.choiceGrid}>{SHARE_CARD_TEMPLATES.map((item) => <Pressable key={item.id} disabled={item.max && !isMax} onPress={() => setTemplate(item.id)} style={[styles.choice, template === item.id && styles.choiceActive, item.max && !isMax && styles.choiceLocked]}><Ionicons name={item.id === 'roadmap' ? 'map' : item.id === 'focus' ? 'flash' : item.id === 'momentum' ? 'pulse' : 'sparkles'} color={template === item.id ? colors.accent : colors.textMuted} size={18} /><Text variant="label" color={template === item.id ? 'accent' : 'secondary'}>{item.label}</Text>{item.max ? <Text variant="caption" color="accent">MAX</Text> : null}</Pressable>)}</View>
    <SectionHeader eyebrow="SIZE" title="Export format" /><View style={styles.choiceGrid}>{(Object.entries(SHARE_CARD_FORMATS) as [ShareCardFormat, (typeof SHARE_CARD_FORMATS)[ShareCardFormat]][]).map(([key, value]) => <Pressable key={key} onPress={() => setFormat(key)} style={[styles.choice, format === key && styles.choiceActive]}><Ionicons name={key === 'vertical' ? 'phone-portrait-outline' : key === 'landscape' ? 'desktop-outline' : 'square-outline'} color={format === key ? colors.accent : colors.textMuted} size={18} /><View><Text variant="label" color={format === key ? 'accent' : 'secondary'}>{value.label}</Text><Text variant="caption" color="muted">{value.width} × {value.height}</Text></View></Pressable>)}</View>
    <Card style={styles.controls}><Text variant="heading">What appears</Text>{([['title', 'Goal title'], ['description', 'Goal description'], ['progress', 'Progress'], ['milestone', 'Current milestone'], ['actions', 'Next actions'], ['targetDate', 'Target date']] as [keyof ShareCardOptions, string][]).map(([key, label]) => <View key={key} style={styles.toggle}><Text style={styles.flex}>{label}</Text><Switch value={options[key]} onValueChange={(value) => setOption(key, value)} trackColor={{ false: colors.border, true: colors.accentMuted }} thumbColor={options[key] ? colors.accent : colors.textMuted} /></View>)}
      {isMax ? <><View style={styles.divider} /><Text variant="eyebrow" color="accent">MAX CUSTOMISATION</Text><Input label="Custom card label" placeholder="MY 90-DAY BUILD" value={subtitle} onChangeText={setSubtitle} /><View style={styles.accents}>{accents.map((value) => <Pressable accessibilityLabel={`Use ${value} accent`} key={value} onPress={() => setAccent(value)} style={[styles.accent, { backgroundColor: value }, accent === value && styles.accentSelected]} />)}</View><View style={styles.toggle}><View style={styles.flex}><Text>DOIT branding</Text><Text variant="caption" color="muted">Keep it on to support DOIT, or hide it with MAX.</Text></View><Switch value={options.branding} onValueChange={(value) => setOption('branding', value)} /></View></> : <View style={styles.brandingNote}><Ionicons name="shield-checkmark" size={18} color={colors.accent} /><Text variant="caption" color="secondary" style={styles.flex}>Tasteful DOIT AI branding is included. MAX can customise or remove it.</Text></View>}
    </Card>
    <View style={styles.actions}><Button label={working === 'download' ? 'Creating PNG…' : 'Download PNG'} icon="download-outline" disabled={Boolean(working)} onPress={() => makeImage('download')} /><Button label={working === 'share' ? 'Preparing…' : 'Share image'} variant="secondary" icon="share-social-outline" disabled={Boolean(working)} onPress={() => makeImage('share')} /><Button label={working === 'copy' ? 'Copying…' : 'Copy text summary'} variant="secondary" icon="copy-outline" disabled={Boolean(working)} onPress={copy} /></View>{working ? <ActivityIndicator color={colors.accent} /> : null}{notice ? <Text variant="caption" color={notice.includes('Could') || notice.includes('unavailable') ? 'danger' : 'accent'} style={styles.center}>{notice}</Text> : null}
  </Screen>;
}

const styles = StyleSheet.create({ screen: { gap: spacing.lg, paddingBottom: spacing.xxxl, paddingTop: spacing.md }, heading: { gap: spacing.sm }, previewFrame: { alignSelf: 'center', maxWidth: 620, width: '100%' }, previewVertical: { maxWidth: 390 }, previewLandscape: { maxWidth: 760 }, preview: { width: '100%' }, choiceGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, choice: { alignItems: 'center', backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.md, borderWidth: 1, flexDirection: 'row', gap: spacing.sm, minHeight: 56, paddingHorizontal: spacing.md }, choiceActive: { backgroundColor: colors.accentMuted, borderColor: colors.accent }, choiceLocked: { opacity: 0.45 }, controls: { gap: spacing.md }, toggle: { alignItems: 'center', borderTopColor: colors.borderSubtle, borderTopWidth: 1, flexDirection: 'row', gap: spacing.md, minHeight: 54, paddingTop: spacing.sm }, divider: { backgroundColor: colors.borderSubtle, height: 1 }, flex: { flex: 1 }, accents: { flexDirection: 'row', gap: spacing.sm }, accent: { borderColor: colors.surface, borderRadius: radius.pill, borderWidth: 3, height: 34, width: 34 }, accentSelected: { borderColor: colors.textPrimary }, brandingNote: { alignItems: 'center', backgroundColor: colors.surfacePressed, borderRadius: radius.md, flexDirection: 'row', gap: spacing.sm, padding: spacing.sm }, actions: { gap: spacing.sm }, center: { textAlign: 'center' }, locked: { alignItems: 'center', gap: spacing.lg, marginTop: spacing.xl, paddingVertical: spacing.xl }, lockIcon: { alignItems: 'center', backgroundColor: colors.accentMuted, borderColor: colors.accentBorder, borderRadius: radius.lg, borderWidth: 1, height: 62, justifyContent: 'center', width: 62 } });
